//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressHierarchy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public int ProvinceId { get; set; }
        public int RegionId { get; set; }
        public int CityId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Province Province { get; set; }
        public virtual Region Region { get; set; }
        public virtual City City { get; set; }
    }
}
