CREATE DATABASE addressheirarchy

GO

USE addressheirarchy

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Location] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [LocationType] INT            NOT NULL,
    [ParentId]     INT            NULL,
    [Name]         NVARCHAR (128) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Location_Location] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[Location] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [IX_Location_LocationType]
    ON [dbo].[Location]([LocationType] ASC);


GO

CREATE TABLE [dbo].[Address] (
    [Id]            INT            IDENTITY (1, 1) NOT NULL,
	[AddressLine1]	NVARCHAR(50)   NOT NULL,	
	[AddressLine2]	NVARCHAR(50)   NULL,	
    [CountryId]     INT            NOT NULL,
    [StateId]       INT            NOT NULL,
    [ProvinceId]    INT            NOT NULL,
    [RegionId]      INT            NOT NULL,
    [CityId]        INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Address_LocationCountry] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Location] ([Id]),
    CONSTRAINT [FK_Address_LocationRegion] FOREIGN KEY ([RegionId]) REFERENCES [dbo].[Location] ([Id]),
    CONSTRAINT [FK_Address_LocationProvince] FOREIGN KEY ([ProvinceId]) REFERENCES [dbo].[Location] ([Id]),
    CONSTRAINT [FK_Address_LocationCity] FOREIGN KEY ([CityId]) REFERENCES [dbo].[Location] ([Id]),
    CONSTRAINT [FK_Address_LocationState] FOREIGN KEY ([StateId]) REFERENCES [dbo].[Location] ([Id])
);

GO

SET IDENTITY_INSERT [dbo].[Location] ON
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (1, 1, NULL, N'ESPAÑA')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (2, 2, 1, N'CATALUNYA')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (3, 3, 2, N'BARCELONA')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (4, 3, 2, N'GIRONA')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (5, 3, 2, N'TARRAGONA')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (6, 3, 2, N'LLEIDA')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (7, 4, 5, N'Terra Alta')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (8, 4, 6, N'Cerdanya')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (9, 4, 5, N'Baix Ebre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (10, 4, 3, N'Barcelonès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (11, 4, 4, N'Osona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (12, 4, 5, N'Ribera d''Ebre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (13, 4, 3, N'Vallès Oriental')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (14, 4, 6, N'Urgell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (15, 4, 6, N'Val d''Aran')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (16, 4, 4, N'Gironès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (17, 4, 6, N'Segrià')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (18, 4, 6, N'Pallars Sobirà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (19, 4, 4, N'Cerdanya')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (20, 4, 6, N'Noguera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (21, 4, 3, N'Vallès Occidental')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (22, 4, 5, N'Tarragonès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (23, 4, 6, N'Segarra')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (24, 4, 3, N'Maresme')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (25, 4, 5, N'Baix Penedès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (26, 4, 3, N'Berguedà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (27, 4, 5, N'Baix Camp')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (28, 4, 4, N'Garrotxa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (29, 4, 6, N'Berguedà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (30, 4, 3, N'Bages')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (31, 4, 3, N'Alt Penedès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (32, 4, 5, N'Conca de Barberà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (33, 4, 4, N'Baix Empordà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (34, 4, 4, N'Ripollès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (35, 4, 5, N'Montsià')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (36, 4, 3, N'Anoia')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (37, 4, 4, N'Selva')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (38, 4, 6, N'Garrigues')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (39, 4, 4, N'Pla de l''Estany')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (40, 4, 6, N'Pla d''Urgell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (41, 4, 6, N'Solsonès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (42, 4, 5, N'Priorat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (43, 4, 3, N'Garraf')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (44, 4, 4, N'Alt Empordà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (45, 4, 5, N'Alt Camp')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (46, 4, 6, N'Alta Ribagorça')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (47, 4, 6, N'Pallars Jussà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (48, 4, 3, N'Baix Llobregat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (49, 4, 6, N'Alt Urgell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (50, 4, 3, N'Osona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (51, 5, 48, N'Abrera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (52, 5, 20, N'Àger')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (53, 5, 14, N'Agramunt')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (54, 5, 45, N'Aiguamúrcia')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (55, 5, 49, N'Alàs i Cerc')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (56, 5, 44, N'Albanyà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (57, 5, 25, N'Albinyana')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (58, 5, 33, N'Albons')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (59, 5, 35, N'Alcanar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (60, 5, 17, N'Alcarràs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (61, 5, 45, N'Alcover')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (62, 5, 9, N'Aldea, L''')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (63, 5, 24, N'Alella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (64, 5, 9, N'Alfara de Carles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (65, 5, 17, N'Alfarràs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (66, 5, 17, N'Alfés')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (67, 5, 20, N'Algerri')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (68, 5, 17, N'Alguaire')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (69, 5, 18, N'Alins')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (70, 5, 19, N'Alp')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (71, 5, 50, N'Alpens')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (72, 5, 18, N'Alt Àneu')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (73, 5, 22, N'Altafulla')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (74, 5, 37, N'Amer')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (75, 5, 9, N'Ametlla de Mar, L''')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (76, 5, 9, N'Ampolla, L''')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (77, 5, 35, N'Amposta')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (78, 5, 37, N'Anglès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (79, 5, 38, N'Arbeca')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (80, 5, 25, N'Arboç, L''')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (81, 5, 27, N'Arbolí')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (82, 5, 37, N'Arbúcies')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (83, 5, 24, N'Arenys de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (84, 5, 24, N'Arenys de Munt')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (85, 5, 24, N'Argentona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (86, 5, 7, N'Arnes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (87, 5, 49, N'Arsèguel')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (88, 5, 20, N'Artesa de Segre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (89, 5, 20, N'Avellanes, Les i Santa Linya')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (90, 5, 26, N'Avià')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (91, 5, 30, N'Avinyó')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (92, 5, 44, N'Avinyonet de Puigventós')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (93, 5, 10, N'Badalona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (94, 5, 26, N'Bagà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (95, 5, 20, N'Balaguer')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (96, 5, 25, N'Banyeres del Penedès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (97, 5, 39, N'Banyoles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (98, 5, 21, N'Barberà del Vallès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (99, 5, 10, N'Barcelona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (100, 5, 20, N'Baronia de Rialb, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (101, 5, 44, N'Bàscara')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (102, 5, 49, N'Bassella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (103, 5, 7, N'Batea')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (104, 5, 48, N'Begues')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (105, 5, 33, N'Begur')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (106, 5, 42, N'Bellmunt del Priorat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (107, 5, 14, N'Bellpuig')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (108, 5, 8, N'Bellver de Cerdanya')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (109, 5, 9, N'Benifallet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (110, 5, 12, N'Benissanet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (111, 5, 26, N'Berga')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (112, 5, 28, N'Besalú')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (113, 5, 13, N'Bigues i Riells')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (114, 5, 33, N'Bisbal d''Empordà, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (115, 5, 37, N'Blanes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (116, 5, 19, N'Bolvir')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (117, 5, 16, N'Bordils')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (118, 5, 38, N'Borges Blanques, Les')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (119, 5, 44, N'Borrassà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (120, 5, 26, N'Borredà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (121, 5, 15, N'Bossòst')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (122, 5, 7, N'Bot')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (123, 5, 27, N'Botarell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (124, 5, 37, N'Breda')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (125, 5, 36, N'Bruc, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (126, 5, 44, N'Cabanelles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (127, 5, 24, N'Cabrera de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (128, 5, 24, N'Cabrils')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (129, 5, 44, N'Cadaqués')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (130, 5, 36, N'Calaf')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (131, 5, 25, N'Calafell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (132, 5, 30, N'Calders')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (133, 5, 37, N'Caldes de Malavella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (134, 5, 13, N'Caldes de Montbui')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (135, 5, 24, N'Caldes d''Estrac')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (136, 5, 24, N'Calella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (137, 5, 33, N'Calonge')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (138, 5, 20, N'Camarasa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (139, 5, 27, N'Cambrils')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (140, 5, 39, N'Camós')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (141, 5, 34, N'Campdevànol')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (142, 5, 34, N'Campelles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (143, 5, 34, N'Camprodon')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (144, 5, 24, N'Canet de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (145, 5, 22, N'Canonja, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (146, 5, 13, N'Canovelles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (147, 5, 13, N'Cànoves i Samalús')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (148, 5, 44, N'Cantallops')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (149, 5, 27, N'Capafonts')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (150, 5, 42, N'Capçanes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (151, 5, 36, N'Capellades')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (152, 5, 13, N'Cardedeu')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (153, 5, 30, N'Cardona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (154, 5, 16, N'Cassà de la Selva')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (155, 5, 47, N'Castell de Mur')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (156, 5, 26, N'Castellar de n''Hug')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (157, 5, 21, N'Castellbisbal')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (158, 5, 38, N'Castelldans')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (159, 5, 48, N'Castelldefels')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (160, 5, 28, N'Castellfollit de la Roca')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (161, 5, 30, N'Castellnou de Bages')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (162, 5, 44, N'Castelló d''Empúries')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (163, 5, 33, N'Castell-Platja d''Aro')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (164, 5, 13, N'Castellterçol')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (165, 5, 37, N'Cellera de Ter, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (166, 5, 16, N'Celrà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (167, 5, 50, N'Centelles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (168, 5, 26, N'Cercs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (169, 5, 21, N'Cerdanyola del Vallès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (170, 5, 48, N'Cervelló')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (171, 5, 23, N'Cervera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (172, 5, 41, N'Clariana de Cardener')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (173, 5, 44, N'Colera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (174, 5, 49, N'Coll de Nargó')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (175, 5, 48, N'Collbató')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (176, 5, 27, N'Colldejou')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (177, 5, 50, N'Collsuspina')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (178, 5, 41, N'Coma, la i Pedra, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (179, 5, 48, N'Corbera de Llobregat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (180, 5, 48, N'Cornellà de Llobregat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (181, 5, 39, N'Cornellà del Terri')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (182, 5, 42, N'Cornudella de Montsant')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (183, 5, 22, N'Creixell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (184, 5, 33, N'Cruïlles, Monells i Sant Sadurní de l''Heura')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (185, 5, 43, N'Cubelles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (186, 5, 20, N'Cubells')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (187, 5, 25, N'Cunit')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (188, 5, 44, N'Darnius')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (189, 5, 9, N'Deltebre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (190, 5, 44, N'Escala, L''')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (191, 5, 32, N'Espluga de Francolí, L''')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (192, 5, 48, N'Esplugues de Llobregat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (193, 5, 44, N'Espolla')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (194, 5, 18, N'Espot')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (195, 5, 26, N'Espunyola, L''')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (196, 5, 49, N'Estamariu')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (197, 5, 18, N'Esterri d''Àneu')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (198, 5, 42, N'Falset')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (199, 5, 18, N'Farrera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (200, 5, 7, N'Fatarella, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (201, 5, 13, N'Figaró-Montmany')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (202, 5, 49, N'Fígols i Alinyà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (203, 5, 44, N'Figueres')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (204, 5, 12, N'Flix')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (205, 5, 13, N'Fogars de Montclús')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (206, 5, 40, N'Fondarella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (207, 5, 33, N'Forallac')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (208, 5, 16, N'Fornells de la Selva')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (209, 5, 13, N'Franqueses del Vallès, Les')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (210, 5, 7, N'Gandesa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (211, 5, 13, N'Garriga, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (212, 5, 44, N'Garriguella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (213, 5, 48, N'Gavà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (214, 5, 19, N'Ger')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (215, 5, 16, N'Girona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (216, 5, 26, N'Gironella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (217, 5, 34, N'Gombrèn')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (218, 5, 29, N'Gósol')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (219, 5, 38, N'Granadella, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (220, 5, 13, N'Granollers')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (221, 5, 23, N'Granyanella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (222, 5, 38, N'Granyena de les Garrigues')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (223, 5, 42, N'Gratallops')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (224, 5, 13, N'Gualba')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (225, 5, 33, N'Gualta')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (226, 5, 26, N'Guardiola de Berguedà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (227, 5, 42, N'Guiamets, Els')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (228, 5, 18, N'Guingueta d''Àneu, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (229, 5, 41, N'Guixers')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (230, 5, 7, N'Horta de Sant Joan')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (231, 5, 10, N'Hospitalet de Llobregat, L''')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (232, 5, 37, N'Hostalric')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (233, 5, 36, N'Igualada')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (234, 5, 19, N'Isòvol')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (235, 5, 40, N'Ivars d''Urgell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (236, 5, 44, N'Jonquera, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (237, 5, 36, N'Jorba')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (238, 5, 49, N'Josa i Tuixén')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (239, 5, 15, N'Les')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (240, 5, 40, N'Linyola')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (241, 5, 18, N'Lladorre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (242, 5, 41, N'Lladurs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (243, 5, 13, N'Llagosta, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (244, 5, 16, N'Llagostera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (245, 5, 34, N'Llanars')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (246, 5, 44, N'Llançà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (247, 5, 18, N'Llavorsí')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (248, 5, 17, N'Lleida')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (249, 5, 44, N'Llers')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (250, 5, 8, N'Lles de Cerdanya')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (251, 5, 47, N'Llimiana')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (252, 5, 19, N'Llívia')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (253, 5, 37, N'Lloret de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (254, 5, 34, N'Llosses, Les')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (255, 5, 50, N'Lluçà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (256, 5, 44, N'Maçanet de Cabrenys')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (257, 5, 37, N'Maçanet de la Selva')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (258, 5, 16, N'Madremanya')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (259, 5, 28, N'Maià de Montcal')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (260, 5, 24, N'Malgrat de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (261, 5, 50, N'Manlleu')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (262, 5, 30, N'Manresa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (263, 5, 42, N'Margalef')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (264, 5, 48, N'Martorell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (265, 5, 35, N'Masdenverge')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (266, 5, 50, N'Masies de Voltregà, Les')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (267, 5, 24, N'Masnou, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (268, 5, 36, N'Masquefa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (269, 5, 42, N'Masroig, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (270, 5, 23, N'Massoteres')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (271, 5, 24, N'Mataró')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (272, 5, 19, N'Meranges')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (273, 5, 40, N'Miralcamp')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (274, 5, 48, N'Molins de Rei')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (275, 5, 40, N'Mollerussa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (276, 5, 44, N'Mollet de Peralada')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (277, 5, 13, N'Mollet del Vallès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (278, 5, 34, N'Molló')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (279, 5, 30, N'Monistrol de Montserrat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (280, 5, 28, N'Montagut i Oix')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (281, 5, 32, N'Montblanc')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (282, 5, 27, N'Montbrió del Camp')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (283, 5, 21, N'Montcada i Reixac')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (284, 5, 8, N'Montellà i Martinet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (285, 5, 49, N'Montferrer i Castellbò')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (286, 5, 36, N'Montmaneu')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (287, 5, 13, N'Montmeló')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (288, 5, 13, N'Montornès del Vallès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (289, 5, 45, N'Mont-ral')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (290, 5, 27, N'Mont-roig del Camp')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (291, 5, 13, N'Montseny')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (292, 5, 12, N'Móra d''Ebre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (293, 5, 12, N'Móra la Nova')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (294, 5, 22, N'Morell, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (295, 5, 42, N'Morera de Montsant, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (296, 5, 15, N'Naut Aran')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (297, 5, 30, N'Navarcles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (298, 5, 30, N'Navàs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (299, 5, 44, N'Navata')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (300, 5, 41, N'Navès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (301, 5, 26, N'Nou de Berguedà, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (302, 5, 41, N'Odèn')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (303, 5, 34, N'Ogassa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (304, 5, 31, N'Olèrdola')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (305, 5, 49, N'Oliana')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (306, 5, 41, N'Olius')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (307, 5, 50, N'Olost')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (308, 5, 28, N'Olot')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (309, 5, 49, N'Organyà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (310, 5, 20, N'Os de Balaguer')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (311, 5, 37, N'Osor')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (312, 5, 24, N'Palafolls')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (313, 5, 33, N'Palafrugell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (314, 5, 33, N'Palamós')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (315, 5, 40, N'Palau d''Anglesola, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (316, 5, 33, N'Palau-sator')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (317, 5, 44, N'Palau-saverdera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (318, 5, 21, N'Palau-solità i Plegamans')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (319, 5, 33, N'Pals')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (320, 5, 48, N'Papiol, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (321, 5, 34, N'Pardines')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (322, 5, 13, N'Parets del Vallès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (323, 5, 32, N'Passanant i Belltall')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (324, 5, 33, N'Pera, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (325, 5, 44, N'Peralada')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (326, 5, 49, N'Peramola')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (327, 5, 9, N'Perelló, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (328, 5, 24, N'Pineda de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (329, 5, 7, N'Pinell de Brai, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (330, 5, 28, N'Planes d''Hostoles, Les')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (331, 5, 34, N'Planoles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (332, 5, 36, N'Pobla de Claramunt, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (333, 5, 26, N'Pobla de Lillet, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (334, 5, 22, N'Pobla de Mafumet, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (335, 5, 47, N'Pobla de Segur, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (336, 5, 42, N'Poboleda')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (337, 5, 49, N'Pont de Bar, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (338, 5, 44, N'Pont de Molins')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (339, 5, 46, N'Pont de Suert, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (340, 5, 32, N'Pontils')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (341, 5, 44, N'Pontós')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (342, 5, 20, N'Ponts')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (343, 5, 39, N'Porqueres')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (344, 5, 42, N'Porrera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (345, 5, 44, N'Port de la Selva, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (346, 5, 44, N'Portbou')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (347, 5, 27, N'Prades')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (348, 5, 7, N'Prat de Comte')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (349, 5, 48, N'Prat de Llobregat, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (350, 5, 27, N'Pratdip')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (351, 5, 50, N'Prats de Lluçanès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (352, 5, 36, N'Prats de Rei, Els')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (353, 5, 8, N'Prats i Sansor')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (354, 5, 24, N'Premià de Dalt')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (355, 5, 24, N'Premià de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (356, 5, 28, N'Preses, Les')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (357, 5, 8, N'Prullans')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (358, 5, 19, N'Puigcerdà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (359, 5, 26, N'Puig-reig')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (360, 5, 36, N'Pujalt')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (361, 5, 34, N'Queralbs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (362, 5, 33, N'Regencós')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (363, 5, 22, N'Renau')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (364, 5, 27, N'Reus')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (365, 5, 18, N'Rialp')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (366, 5, 12, N'Riba-roja d''Ebre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (367, 5, 49, N'Ribera d''Urgellet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (368, 5, 34, N'Ribes de Freser')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (369, 5, 37, N'Riells i Viabrea')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (370, 5, 22, N'Riera de Gaià, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (371, 5, 41, N'Riner')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (372, 5, 34, N'Ripoll')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (373, 5, 21, N'Ripollet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (374, 5, 8, N'Riu de Cerdanya')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (375, 5, 37, N'Riudarenes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (376, 5, 27, N'Riudecanyes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (377, 5, 37, N'Riudellots de la Selva')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (378, 5, 27, N'Riudoms')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (379, 5, 50, N'Roda de Ter')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (380, 5, 44, N'Roses')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (381, 5, 21, N'Rubí')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (382, 5, 50, N'Rupit i Pruit')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (383, 5, 21, N'Sabadell')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (384, 5, 26, N'Sagàs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (385, 5, 47, N'Salàs de Pallars')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (386, 5, 26, N'Saldes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (387, 5, 28, N'Sales de Llierca')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (388, 5, 30, N'Sallent')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (389, 5, 22, N'Salomó')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (390, 5, 22, N'Salou')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (391, 5, 16, N'Salt')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (392, 5, 10, N'Sant Adrià de Besòs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (393, 5, 48, N'Sant Andreu de la Barca')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (394, 5, 24, N'Sant Andreu de Llavaneres')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (395, 5, 28, N'Sant Aniol de Finestres')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (396, 5, 13, N'Sant Antoni de Vilamajor')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (397, 5, 50, N'Sant Bartomeu del Grau')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (398, 5, 48, N'Sant Boi de Llobregat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (399, 5, 50, N'Sant Boi de Lluçanès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (400, 5, 35, N'Sant Carles de la Ràpita')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (401, 5, 24, N'Sant Cebrià de Vallalta')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (402, 5, 13, N'Sant Celoni')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (403, 5, 44, N'Sant Climent Sescebes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (404, 5, 21, N'Sant Cugat del Vallès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (405, 5, 13, N'Sant Esteve de Palautordera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (406, 5, 48, N'Sant Esteve Sesrovires')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (407, 5, 33, N'Sant Feliu de Guíxols')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (408, 5, 48, N'Sant Feliu de Llobregat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (409, 5, 28, N'Sant Feliu de Pallerols')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (410, 5, 28, N'Sant Ferriol')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (411, 5, 30, N'Sant Fruitós de Bages')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (412, 5, 37, N'Sant Hilari Sacalm')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (413, 5, 26, N'Sant Jaume de Frontanyà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (414, 5, 25, N'Sant Jaume dels Domenys')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (415, 5, 34, N'Sant Joan de les Abadesses')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (416, 5, 30, N'Sant Joan de Vilatorrada')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (417, 5, 48, N'Sant Joan Despí')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (418, 5, 28, N'Sant Joan les Fonts')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (419, 5, 16, N'Sant Julià de Ramis')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (420, 5, 50, N'Sant Julià de Vilatorta')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (421, 5, 48, N'Sant Just Desvern')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (422, 5, 44, N'Sant Llorenç de la Muga')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (423, 5, 41, N'Sant Llorenç de Morunys')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (424, 5, 21, N'Sant Llorenç Savall')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (425, 5, 14, N'Sant Martí de Riucorb')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (426, 5, 31, N'Sant Martí Sarroca')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (427, 5, 34, N'Sant Pau de Segúries')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (428, 5, 43, N'Sant Pere de Ribes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (429, 5, 31, N'Sant Pere de Riudebitlles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (430, 5, 44, N'Sant Pere Pescador')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (431, 5, 24, N'Sant Pol de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (432, 5, 50, N'Sant Quirze de Besora')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (433, 5, 13, N'Sant Quirze Safaja')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (434, 5, 23, N'Sant Ramon')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (435, 5, 31, N'Sant Sadurní d''Anoia')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (436, 5, 50, N'Sant Sadurní d''Osormort')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (437, 5, 30, N'Sant Vicenç de Castellet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (438, 5, 24, N'Sant Vicenç de Montalt')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (439, 5, 35, N'Santa Bàrbara')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (440, 5, 37, N'Santa Coloma de Farners')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (441, 5, 10, N'Santa Coloma de Gramenet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (442, 5, 32, N'Santa Coloma de Queralt')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (443, 5, 33, N'Santa Cristina d''Aro')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (444, 5, 50, N'Santa Eugènia de Berga')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (445, 5, 31, N'Santa Margarida i els Monjos')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (446, 5, 50, N'Santa Maria de Corcó')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (447, 5, 26, N'Santa Maria de Merlès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (448, 5, 13, N'Santa Maria de Palautordera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (449, 5, 30, N'Santa Maria d''Oló')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (450, 5, 28, N'Santa Pau')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (451, 5, 21, N'Santa Perpètua de Mogoda')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (452, 5, 24, N'Santa Susanna')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (453, 5, 30, N'Santpedor')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (454, 5, 16, N'Sarrià de Ter')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (455, 5, 44, N'Saus')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (456, 5, 44, N'Selva de Mar, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (457, 5, 27, N'Selva del Camp, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (458, 5, 35, N'Sénia, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (459, 5, 34, N'Setcases')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (460, 5, 49, N'Seu d''Urgell, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (461, 5, 50, N'Seva')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (462, 5, 37, N'Sils')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (463, 5, 43, N'Sitges')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (464, 5, 32, N'Solivella')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (465, 5, 41, N'Solsona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (466, 5, 18, N'Soriguera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (467, 5, 18, N'Sort')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (468, 5, 31, N'Subirats')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (469, 5, 30, N'Súria')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (470, 5, 37, N'Susqueda')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (471, 5, 22, N'Tarragona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (472, 5, 14, N'Tàrrega')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (473, 5, 50, N'Tavèrnoles')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (474, 5, 50, N'Tavertet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (475, 5, 44, N'Terrades')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (476, 5, 21, N'Terrassa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (477, 5, 18, N'Tírvia')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (478, 5, 12, N'Tivissa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (479, 5, 50, N'Tona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (480, 5, 23, N'Torà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (481, 5, 24, N'Tordera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (482, 5, 50, N'Torelló')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (483, 5, 47, N'Torre de Cabdella, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (484, 5, 22, N'Torredembarra')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (485, 5, 17, N'Torrefarrera')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (486, 5, 31, N'Torrelles de Foix')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (487, 5, 48, N'Torrelles de Llobregat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (488, 5, 33, N'Torrent')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (489, 5, 17, N'Torres de Segre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (490, 5, 44, N'Torroella de Fluvià')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (491, 5, 33, N'Torroella de Montgrí')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (492, 5, 42, N'Torroja del Priorat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (493, 5, 28, N'Tortellà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (494, 5, 9, N'Tortosa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (495, 5, 34, N'Toses')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (496, 5, 37, N'Tossa de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (497, 5, 47, N'Tremp')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (498, 5, 35, N'Ulldecona')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (499, 5, 42, N'Ulldemolins')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (500, 5, 19, N'Urús')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (501, 5, 46, N'Vall de Boí, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (502, 5, 18, N'Vall de Cardós')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (503, 5, 28, N'Vall d''en Bas, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (504, 5, 14, N'Vallbona de les Monges')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (505, 5, 26, N'Vallcebre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (506, 5, 32, N'Vallfogona de Riucorb')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (507, 5, 48, N'Vallirana')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (508, 5, 33, N'Vall-llobrega')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (509, 5, 13, N'Vallromanes')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (510, 5, 45, N'Valls')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (511, 5, 49, N'Valls de Valira, Les')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (512, 5, 27, N'Vandellòs i l''Hospitalet de l''Infant')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (513, 5, 25, N'Vendrell, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (514, 5, 33, N'Verges')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (515, 5, 50, N'Vic')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (516, 5, 11, N'Vidrà')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (517, 5, 37, N'Vidreres')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (518, 5, 15, N'Vielha e Mijaran')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (519, 5, 44, N'Vilabertran')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (520, 5, 44, N'Viladamat')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (521, 5, 48, N'Viladecans')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (522, 5, 39, N'Vilademuls')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (523, 5, 11, N'Viladrau')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (524, 5, 44, N'Vilafant')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (525, 5, 31, N'Vilafranca del Penedès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (526, 5, 14, N'Vilagrassa')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (527, 5, 44, N'Vilajuïga')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (528, 5, 7, N'Vilalba dels Arcs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (529, 5, 46, N'Vilaller')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (530, 5, 34, N'Vilallonga de Ter')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (531, 5, 17, N'Vilanova de la Barca')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (532, 5, 20, N'Vilanova de Meià')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (533, 5, 50, N'Vilanova de Sau')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (534, 5, 13, N'Vilanova del Vallès')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (535, 5, 27, N'Vilanova d''Escornalbou')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (536, 5, 43, N'Vilanova i la Geltrú')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (537, 5, 22, N'Vila-seca')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (538, 5, 24, N'Vilassar de Mar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (539, 5, 32, N'Vilaverd')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (540, 5, 42, N'Vilella Baixa, La')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (541, 5, 37, N'Vilobí d''Onyar')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (542, 5, 38, N'Vilosell, El')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (543, 5, 32, N'Vimbodí i Poblet')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (544, 5, 12, N'Vinebre')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (545, 5, 27, N'Vinyols i els Arcs')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (546, 5, 26, N'Viver i Serrateix')
INSERT INTO [dbo].[Location] ([Id], [LocationType], [ParentId], [Name]) VALUES (547, 5, 9, N'Xerta')
SET IDENTITY_INSERT [dbo].[Location] OFF


